AME-3041 Add support for cluster autoscaler settings
avisi-cloud/go-client pull request #24
Opened 2024-09-11 12:35 UTC by HugUlf

2024-10-01 08:34 UTC, djmarkoz commented on pkg/acloudapi/apitypes.go
> +	AutoScalerSettings           AutoscalingSettings    `json:"clusterAutoscalerSettings,omitempty" yaml:"ClusterAutoScalerSettings,omitempty"`
This should be a pointer 
```suggestion
	AutoScalerSettings           *AutoscalingSettings    `json:"clusterAutoscalerSettings,omitempty" yaml:"ClusterAutoScalerSettings,omitempty"`
```

2024-10-01 08:34 UTC, djmarkoz requested changes

2024-10-01 08:34 UTC, djmarkoz commented on pkg/acloudapi/apitypes.go
> +	AutoScalerSettings AutoscalingSettings `json:"clusterAutoscalerSettings,omitempty" yaml:"ClusterAutoScalerSettings,omitempty"`
This should be a pointer 

```suggestion
	AutoScalerSettings *AutoscalingSettings `json:"clusterAutoscalerSettings,omitempty" yaml:"ClusterAutoScalerSettings,omitempty"`
```

2024-10-03 11:08 UTC, djmarkoz commented on pkg/acloudapi/apitypes.go
> +	AutoScalerSettings          AutoscalingSettings `json:"clusterAutoscalerSettings,omitempty" yaml:"ClusterAutoScalerSettings,omitempty"`
I think we should use a pointer here aswel.

2024-10-03 12:19 UTC, idebeijer approved these changes
LGTM

2024-10-03 12:19 UTC, djmarkoz approved these changes

2024-10-03 12:29 UTC, merged